function [S, platforms, globals] = SWIFT_nc_schema()
% Variable metadata (whitelist) for SWIFT2NC_v2
%
%   [S, platforms, globals] = SWIFT_nc_schema()
%
% S mirrors the SWIFT struct tree. Each leaf is a struct of netCDF
% attributes for that field; only fields listed here are written. The
% field 'name' is the netCDF variable name (default: SWIFT field name) and
% is not written as an attribute.
%
% Attribute values may contain {key} placeholders, filled from
% platforms.(v3|v4|micro); an attribute that resolves to '' is omitted.
% {at_ct_depth} and {at_met_height} are ' at 0.66 m depth' style phrases
% made from SWIFT.CTdepth and SWIFT.metheight (set in readSWIFT_SBD), or ''
% when the data has no height.
% globals are global attributes, with the same placeholders.
%
% Oct 2026 by M. LeClair (mleclair); metadata ported from SWIFT2NC
% (L. Hosekova, S. Iyer, J. Thomson)

%% Platforms
platforms.v3 = struct( ...
    'imu', 'Microstrain 3DM-GX3-35/AHRS', ...
    'met', 'Airmar 200WX', ...
    'adcp', 'Nortek Aquadopp ADCP', ...
    'ct', 'Aanderaa 4319', ...
    'description', 'Data collected from Surface Wave Instrument Float with Tracking (SWIFT) {id}. See www.apl.uw.edu/SWIFT for more information', ...
    'temporal_sampling', 'Data are ensemble values calculated from 512 secs of raw data recorded at 4 Hz.', ...
    'platform_reference', 'Thomson, J., (2012). Wave breaking dissipation observed with SWIFT drifters, Journal of Atmospheric and Oceanic Technology, http://dx.doi.org/10.1175/JTECH-D-12-00018.1');
platforms.v4 = platforms.v3;
platforms.v4.imu = 'SBG Ellipse/AHRS';
platforms.v4.met = 'Vaisala WXT530';
platforms.v4.adcp = 'Nortek Signature 1000 ADCP with AHRS';
platforms.micro = struct( ...
    'imu', 'GPSWaves / NEDwaves', ...
    'met', '', ...
    'adcp', '', ...
    'ct', 'Aanderaa 4319', ...
    'description', 'Data collected from microSWIFT {id}. See www.apl.uw.edu/SWIFT for more information', ...
    'temporal_sampling', 'Data are ensemble values calculated from 1024 secs of raw data recorded at 4 Hz.', ...
    'platform_reference', 'Thomson et al, Development and testing of microSWIFT expendable wave buoys, Coastal Engineering Journal, https://doi.org/10.1080/21664250.2023.2283325');

%% Global attributes
globals = struct( ...
    'Conventions', 'CF-1.8', ...
    'creator', 'Jim Thomson (APL-UW)', ...
    'please_acknowledge', 'investigator above', ...
    'institution', 'Applied Physics Laboratory at the University of Washington (APL-UW)', ...
    'contact_email_1', 'jthomson@apl.washington.edu', ...
    'description', '{description}', ...
    'temporal_sampling', '{temporal_sampling}', ...
    'reference1', '{platform_reference}', ...
    'reference2', 'https://github.com/SASlabgroup/SWIFT-codes, https://doi.org/10.5281/zenodo.13922183');

%% Shared text
wavemethod = 'Wave spectral processing as shown in Thomson et al., JTech, 2018.';
atmet = '{at_met_height}';
atct = '{at_ct_depth}';

%% Burst identification and position
S.time = struct('units', 'seconds since 1970-01-01 00:00:00', ...
    'long_name', 'time', 'standard_name', 'time');
S.ID = struct('name', 'platform_id');
S.burstID = struct('name', 'burst_id', 'long_name', 'burst identifier');
S.date = struct('long_name', 'burst date as stored by readSWIFT_SBD');
S.sbdfile = struct('name', 'sbd_file', 'long_name', 'raw SBD file name');
S.lat = struct('units', 'degree_north', 'long_name', 'latitude', ...
    'standard_name', 'latitude', 'instrument', 'GPS');
S.lon = struct('units', 'degree_east', 'long_name', 'longitude', ...
    'standard_name', 'longitude', 'instrument', 'GPS');
S.driftspd = struct('name', 'drift_speed', 'units', 'm/s', ...
    'long_name', 'platform drift speed (equivalent to speed over ground)', ...
    'standard_name', 'platform_speed_wrt_ground', 'instrument', 'GPS');
S.driftspdstddev = struct('name', 'drift_speed_stddev', 'units', 'm/s', ...
    'long_name', 'standard deviation of platform drift speed', 'instrument', 'GPS');
S.driftdirT = struct('name', 'drift_direction', 'units', 'degree', ...
    'long_name', 'platform drift direction toward, degrees from north (course over ground)', ...
    'standard_name', 'platform_course', 'instrument', 'GPS');
S.driftdirTstddev = struct('name', 'drift_direction_stddev', 'units', 'degree', ...
    'long_name', 'standard deviation of platform drift direction', 'instrument', 'GPS');

%% Ocean
S.watertemp = struct('name', 'sea_water_temperature', 'units', 'degree_C', ...
    'long_name', ['sea water temperature' atct], ...
    'standard_name', 'sea_water_temperature', 'instrument', '{ct}');
S.watertempstddev = struct('name', 'sea_water_temperature_stddev', 'units', 'degree_C', ...
    'long_name', ['standard deviation of sea water temperature' atct], 'instrument', '{ct}');
S.watertemp_d2 = struct('name', 'sea_water_temperature_at_depth', 'units', 'degree_C', ...
    'long_name', 'sea water temperature from second CT sensor', ...
    'standard_name', 'sea_water_temperature', 'instrument', '{ct}');
% S.watertemp2 = struct('name', 'sea_water_temperature_adcp', 'units', 'degree_C', ...
%     'long_name', 'sea water temperature from the ADCP internal sensor (burst mean)', ...
%     'standard_name', 'sea_water_temperature', 'instrument', '{adcp}');
S.salinity = struct('name', 'sea_water_salinity', 'units', 'psu', ...
    'long_name', ['sea water salinity' atct], ...
    'standard_name', 'sea_water_salinity', 'instrument', '{ct}');
S.salinitystddev = struct('name', 'sea_water_salinity_stddev', 'units', 'psu', ...
    'long_name', ['standard deviation of sea water salinity' atct], 'instrument', '{ct}');
S.salinity_d2 = struct('name', 'sea_water_salinity_at_depth', 'units', 'psu', ...
    'long_name', 'sea water salinity from second CT sensor', ...
    'standard_name', 'sea_water_salinity', 'instrument', '{ct}');
S.CTdepth = struct('name', 'ct_depth', 'units', 'm', ...
    'long_name', 'nominal depth of the CT sensor (set by port in readSWIFT_SBD)');
S.qsea = struct('name', 'sea_surface_saturation_specific_humidity', 'units', 'g/kg', ...
    'long_name', ['sea surface saturation specific humidity from sea water temperature' atct], ...
    'standard_name', 'surface_specific_humidity');

%% Atmosphere
S.airtemp = struct('name', 'air_temperature', 'units', 'degree_C', ...
    'long_name', ['air temperature' atmet], ...
    'standard_name', 'air_temperature', 'instrument', '{met}');
S.airtempstddev = struct('name', 'air_temperature_stddev', 'units', 'degree_C', ...
    'long_name', ['standard deviation of air temperature' atmet], 'instrument', '{met}');
S.airpres = struct('name', 'air_pressure', 'units', 'hPa', ...
    'long_name', ['air pressure' atmet], ...
    'standard_name', 'air_pressure', 'instrument', '{met}');
S.airpresstddev = struct('name', 'air_pressure_stddev', 'units', 'hPa', ...
    'long_name', ['standard deviation of air pressure' atmet], 'instrument', '{met}');
S.relhumidity = struct('name', 'relative_humidity', 'units', '%', ...
    'long_name', ['relative humidity' atmet], ...
    'standard_name', 'relative_humidity', 'instrument', '{met}');
S.relhumiditystddev = struct('name', 'relative_humidity_stddev', 'units', '%', ...
    'long_name', ['standard deviation of relative humidity' atmet], 'instrument', '{met}');
S.qair = struct('name', 'specific_humidity', 'units', 'g/kg', ...
    'long_name', ['specific humidity' atmet], 'standard_name', 'specific_humidity', ...
    'method', 'calculated from air temperature, air pressure, and relative humidity');
S.windspd = struct('name', 'wind_speed', 'units', 'm/s', ...
    'long_name', ['true wind speed' atmet], ...
    'standard_name', 'wind_speed', 'instrument', '{met}');
S.windspdstddev = struct('name', 'wind_speed_stddev', 'units', 'm/s', ...
    'long_name', ['standard deviation of true wind speed' atmet], 'instrument', '{met}');
S.windspdskew = struct('name', 'wind_speed_skewness', 'units', '1', ...
    'long_name', ['skewness of true wind speed' atmet], 'instrument', '{met}');
S.windspdkurt = struct('name', 'wind_speed_kurtosis', 'units', '1', ...
    'long_name', ['kurtosis of true wind speed' atmet], 'instrument', '{met}');
S.winddirT = struct('name', 'wind_direction', 'units', 'degree', ...
    'long_name', ['true wind direction' atmet ', direction from north'], ...
    'standard_name', 'wind_from_direction', 'instrument', '{met}');
S.winddirTstddev = struct('name', 'wind_direction_stddev', 'units', 'degree', ...
    'long_name', ['standard deviation of true wind direction' atmet], 'instrument', '{met}');
S.winddirR = struct('name', 'wind_direction_relative', 'units', 'degree', ...
    'long_name', ['wind direction relative to the platform' atmet], 'instrument', '{met}');
S.winddirRstddev = struct('name', 'wind_direction_relative_stddev', 'units', 'degree', ...
    'long_name', ['standard deviation of relative wind direction' atmet], 'instrument', '{met}');
S.metheight = struct('name', 'met_height', 'units', 'm', ...
    'long_name', 'nominal height of the met sensor (set in readSWIFT_SBD)');
S.tilt = struct('units', 'degree', 'long_name', 'tilt of the met sensor from vertical', ...
    'instrument', '{met}');
S.tiltstd = struct('name', 'tilt_stddev', 'units', 'degree', ...
    'long_name', 'standard deviation of met sensor tilt', 'instrument', '{met}');
S.puck = struct('long_name', 'three color channels of a WetLabs puck fluorometer');

%% Waves
S.sigwaveheight = struct('name', 'significant_wave_height', 'units', 'm', ...
    'long_name', 'significant wave height', ...
    'standard_name', 'sea_surface_wave_significant_height', 'instrument', '{imu}');
S.sigwaveheight_alt = struct('name', 'significant_wave_height_alt', 'units', 'm', ...
    'long_name', 'alternate significant wave height (reprocess_SBG)', 'instrument', '{imu}');
S.peakwaveperiod = struct('name', 'peak_wave_period', 'units', 's', ...
    'long_name', 'period at the peak of the wave spectrum', ...
    'standard_name', 'sea_surface_wave_period_at_variance_spectral_density_maximum', ...
    'instrument', '{imu}', 'method', wavemethod);
S.peakwaveperiod_alt = struct('name', 'peak_wave_period_alt', 'units', 's', ...
    'long_name', 'alternate peak wave period (reprocess_SBG)', 'instrument', '{imu}');
S.peakwavedirT = struct('name', 'peak_wave_direction', 'units', 'degree', ...
    'long_name', 'wave direction at spectral peak, direction from north', ...
    'standard_name', 'sea_surface_wave_from_direction_at_variance_spectral_density_maximum', ...
    'instrument', '{imu}', 'method', wavemethod);
S.centroidwaveperiod = struct('name', 'mean_wave_period', 'units', 's', ...
    'long_name', 'energy-weighted (centroid) wave period, ratio of zeroth to first spectral moment', ...
    'standard_name', 'sea_surface_wave_mean_period', 'instrument', '{imu}');
S.mss = struct('name', 'wave_mean_square_slope', 'units', '1', ...
    'long_name', 'wave mean square slope', 'instrument', '{imu}', ...
    'method', 'Calculated with equation 4 in Iyer et al., JGR Oceans, 2022.');
S.ustar = struct('name', 'friction_velocity_from_wave_spectra', 'units', 'm/s', ...
    'long_name', 'friction velocity in air from wave spectra', ...
    'standard_name', 'friction_velocity_in_air', 'instrument', '{imu}', ...
    'method', 'Calculated with equation 3 in Iyer et al., JGR Oceans, 2022.');

S.wavespectra.freq = struct('name', 'frequency', 'units', 'Hz', ...
    'long_name', 'spectral frequencies', 'standard_name', 'wave_frequency', ...
    'instrument', '{imu}');
S.wavespectra.energy = struct('name', 'energy_density', 'units', 'm^2/Hz', ...
    'long_name', 'wave energy spectral density as a function of frequency', ...
    'standard_name', 'sea_surface_wave_variance_spectral_density', ...
    'instrument', '{imu}', 'method', wavemethod);
S.wavespectra.a1 = struct('units', '1', ...
    'long_name', 'normalized spectral directional moment (positive east)', ...
    'instrument', '{imu}', 'method', wavemethod);
S.wavespectra.b1 = struct('units', '1', ...
    'long_name', 'normalized spectral directional moment (positive north)', ...
    'instrument', '{imu}', 'method', wavemethod);
S.wavespectra.a2 = struct('units', '1', ...
    'long_name', 'normalized spectral directional moment (east-west)', ...
    'instrument', '{imu}', 'method', wavemethod);
S.wavespectra.b2 = struct('units', '1', ...
    'long_name', 'normalized spectral directional moment (north-south)', ...
    'instrument', '{imu}', 'method', wavemethod);
S.wavespectra.check = struct('name', 'check_factor', 'units', '1', ...
    'long_name', 'spectral check factor (should be near 1)', ...
    'instrument', '{imu}', 'method', wavemethod);

%% Currents and turbulence (Signature ADCP, v4)
S.signature.profile.z = struct('name', 'depth', 'units', 'm', 'positive', 'down', ...
    'long_name', 'depth bins for currents', 'standard_name', 'depth');
S.signature.profile.east = struct('name', 'eastward_velocity', 'units', 'm/s', ...
    'long_name', 'eastward currents relative to the float', ...
    'standard_name', 'eastward_sea_water_velocity', 'instrument', '{adcp}');
S.signature.profile.north = struct('name', 'northward_velocity', 'units', 'm/s', ...
    'long_name', 'northward currents relative to the float', ...
    'standard_name', 'northward_sea_water_velocity', 'instrument', '{adcp}');
S.signature.profile.w = struct('name', 'upward_velocity', 'units', 'm/s', ...
    'long_name', 'vertical velocity relative to the float', ...
    'standard_name', 'upward_sea_water_velocity', 'instrument', '{adcp}');
S.signature.profile.uvar = struct('name', 'eastward_velocity_variance', 'units', 'm^2/s^2', ...
    'long_name', 'within-burst variance of eastward velocity', 'instrument', '{adcp}');
S.signature.profile.vvar = struct('name', 'northward_velocity_variance', 'units', 'm^2/s^2', ...
    'long_name', 'within-burst variance of northward velocity', 'instrument', '{adcp}');
S.signature.profile.wvar = struct('name', 'upward_velocity_variance', 'units', 'm^2/s^2', ...
    'long_name', 'within-burst variance of vertical velocity', 'instrument', '{adcp}');
S.signature.profile.spd_alt = struct('name', 'speed_alt', 'units', 'm/s', ...
    'long_name', 'horizontal speed computed before burst averaging (fix for bad heading/pitch/roll)', ...
    'instrument', '{adcp}');

S.signature.HRprofile.z = struct('name', 'depth', 'units', 'm', 'positive', 'down', ...
    'long_name', 'depth bins for high-resolution profiles', 'standard_name', 'depth');
S.signature.HRprofile.w = struct('name', 'upward_velocity', 'units', 'm/s', ...
    'long_name', 'vertical velocity from high-resolution mode', ...
    'standard_name', 'upward_sea_water_velocity', 'instrument', '{adcp}');
S.signature.HRprofile.wvar = struct('name', 'upward_velocity_variance', 'units', 'm^2/s^2', ...
    'long_name', 'within-burst variance of high-resolution vertical velocity', 'instrument', '{adcp}');
S.signature.HRprofile.tkedissipationrate = struct('name', 'tke_dissipation_rate', 'units', 'W/kg', ...
    'long_name', 'turbulent dissipation rate from high-resolution mode', ...
    'standard_name', 'specific_turbulent_kinetic_energy_dissipation_in_sea_water', ...
    'instrument', '{adcp}');

S.signature.echoz = struct('name', 'echo_depth', 'units', 'm', 'positive', 'down', ...
    'long_name', 'depth bins for echogram (sound speed corrected per burst)');
S.signature.echo = struct('name', 'echo_intensity', 'units', 'dB', ...
    'long_name', 'echogram intensity corrected for spreading and attenuation', ...
    'instrument', '{adcp}');
S.signature.altimeter = struct('name', 'altimeter_distance', 'units', 'm', ...
    'long_name', 'altimeter distance to seafloor', 'instrument', '{adcp}');

%% Currents and turbulence (Aquadopp, v3)
S.uplooking.z = struct('name', 'depth', 'units', 'm', 'positive', 'down', ...
    'long_name', 'depth bins for the tke dissipation rate profiles', 'standard_name', 'depth');
S.uplooking.tkedissipationrate = struct('name', 'tke_dissipation_rate', 'units', 'W/kg', ...
    'long_name', 'turbulent dissipation rate beneath the wave-following free surface', ...
    'standard_name', 'specific_turbulent_kinetic_energy_dissipation_in_sea_water', ...
    'instrument', '{adcp}');
S.downlooking.z = struct('name', 'depth', 'units', 'm', 'positive', 'down', ...
    'long_name', 'depth bins for the velocity profiles', 'standard_name', 'depth');
S.downlooking.velocityprofile = struct('name', 'velocity_magnitude', 'units', 'm/s', ...
    'long_name', 'horizontal velocity magnitude relative to the float (not corrected for drift)', ...
    'instrument', '{adcp}');

end
