#!/bin/bash
# Run record and send volt data for microSWIFT

#directories and files needed 
voltDir=/home/pi/microSWIFT/sensors
config=/home/pi/microSWIFT/utils/Config.dat
utilsDir=/home/pi/microSWIFT/utils

#get PIDs  
voltPID=$(ps -ef | grep "recordVolt.py" | grep -v grep | awk '{ print $2 }')
echo "voltPID=" $voltPID

#add directories needed to run volt app to pythonpath
export PYTHONPATH=$PYTHONPATH/$voltDir:/$utilsDir

#=================================================================================
#Run app
#=================================================================================
echo "" 
echo " --- RUN RECORD VOLT ---"
python3 recordVolt.py $config &