#!/bin/bash

dataDir=/home/pi/microSWIFT/data/
source /home/pi/microSWIFT/utils/Config.dat

timeStamp=$(date -u '+%d%b%y_%H:%M:%S')

fileName=$floatID"_cpuTempandWifi_"$timeStamp"UTC.dat"
echo $timeStamp

while true; 
do
	sleep 1
	echo $timeStamp >> $dataDir/$fileName
	vcgencmd measure_temp >> $dataDir/$fileName
	vcgencmd measure_temp

	echo $timeStamp >> $dataDir/$fileName
	ping -c 1 192.168.0.28 &> /dev/null && echo success || echo fail >> $dataDir/$fileName
	ping -c 1 192.168.0.28 &> /dev/null && echo success || echo fail
done
