#!/bin/bash

#read config file 
source /home/pi/microSWIFT/utils/Config.dat

#host username to send data to 
USERNAME=$shipUser
#host IP address to send data to 
HOST=$shipIP
#data and log directories in this pi
DATAPATH=$dataDir
LOGPATH=$logDir
#create new directory with floatID in config file 
REMOTEPATH=$shipDir/microSWIFT$floatID
#host password to send data to
PASSWORD=$shipPass

#initialize send data flag 
sendData=0

#turn wifi on 
sudo rfkill unblock wifi

#will most likely happen at the same time 
while [ "$sendData" -eq 0 ]
do 
    #try to find server to connect to 
    ping -c 1 $HOST ; echo $?

    #0 means host reachable
    #2 means unreachable
    if [ "$?" = 0 ]
    then 
        echo "Host found" 
        sshpass -p $PASSWORD scp -r $DATAPATH $USERNAME@$HOST:$REMOTEPATH
	sshpass -p $PASSWORD scp -r $LOGPATH $USERNAME@$HOST:$REMOTEPATH
        sendData=1
    else 
        echo "Host not found" 
    fi
	
done
