#! /bin/bash

echo "this is setTime"
file='/home/pi/microSWIFT/data/setTime'
dayTime=$(cat "$file")
echo $dayTime

month=${dayTime:0:2}
day=${dayTime:2:2}
hour=${dayTime:4:2}
minute=${dayTime:6:2}
sec=${dayTime:8:2}
year=${dayTime:10:4}

echo $month
echo $day
echo $hour
echo $minute
echo $sec
echo $year

sudo date --set "$year-$month-$day $hour:$minute:$sec"